# -*- coding: utf-8 -*-
"""flower_class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2Nl7QKRdrvbU25blhBCp3k5HJthaMKB
"""

import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score
iris = load_iris()

X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target
X = X.fillna(X.mean())
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
split_ratios = [0.5, 0.6, 0.7, 0.8]
k_values = [1, 3, 5, 7, 9]

results = []
for ratio in split_ratios:
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=(1 - ratio), random_state=42
    )

    for k in k_values:
        knn = KNeighborsClassifier(n_neighbors=k)
        knn.fit(X_train, y_train)

        y_pred = knn.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        prec = precision_score(y_test, y_pred, average='macro')
        rec = recall_score(y_test, y_pred, average='macro')
        f1 = f1_score(y_test, y_pred, average='macro')

        results.append([ratio, k, acc, prec, rec, f1])
        results_df = pd.DataFrame(
    results,
    columns=["Train Ratio", "K Value", "Accuracy", "Precision", "Recall", "F1 Score"]
)

print(results_df)
best_result = results_df.loc[results_df["Accuracy"].idxmax()]
print("\nBest Model Configuration:")
print(best_result)
best_ratio = best_result["Train Ratio"]
best_k = int(best_result["K Value"])

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=(1 - best_ratio), random_state=42
)

best_knn = KNeighborsClassifier(n_neighbors=best_k)
best_knn.fit(X_train, y_train)

y_pred = best_knn.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)